#!/usr/bin/env php
<?php
/*
 * --------------------------------------------------------------------------
 * Bootgly PHP Framework
 * Developed by Rodrigo Vieira (@rodrigoslayertech)
 * Copyright 2023-present
 * Licensed under MIT
 * --------------------------------------------------------------------------
 */

#error_reporting(E_ALL); ini_set('display_errors', 'On');

#phpinfo(); exit;

(@include __DIR__ . '/@imports/autoload.php') || exit('Type `composer install` to install dependencies.' . PHP_EOL);
